// This file is generated by Sapper — do not edit it!
export const timestamp = 1539309760816;

export const files = [
	"favicon.png",
	"global.css",
	"great-success.png",
	"manifest.json",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];
export { files as assets }; // legacy

export const shell = [
	"client/5bd0b103cd633d82ae80/about.about.js",
	"client/5bd0b103cd633d82ae80/blog.blog.js",
	"client/5bd0b103cd633d82ae80/blog_$slug.blog_$slug.js",
	"client/5bd0b103cd633d82ae80/index.index.js",
	"client/5bd0b103cd633d82ae80/main.js",
	"client/5bd0b103cd633d82ae80/0.0.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/about\/?$/ },
	{ pattern: /^\/blog\/?$/ },
	{ pattern: /^\/blog\/([^\/]+?)\/?$/ }
];